Repository wanted-wecode-subjects/humanscape-subject, pull requests merged in 2021-11, with the labels that each got.

#3 feat: 임상 초기 세팅
  src/app.module.ts
  src/clinical/clinical.controller.ts
  src/clinical/clinical.module.ts
  src/clinical/clinical.repository.ts
  src/clinical/clinical.service.ts
  src/clinical/entities/clinical.entity.ts
Labels: feat

#6 feat: step 초기 세팅
  eight-percent.db
  src/app.module.ts
  src/clinical/clinical.service.ts
  src/step/dto/create-step.dto.ts
  src/step/dto/update-step.dto.ts
  src/step/entities/step.entity.ts
  src/step/step.controller.ts
  src/step/step.module.ts
  src/step/step.service.ts
Labels: feat

#11 feat: step create
  src/step/dto/create-step.dto.ts
  src/step/entities/step.entity.ts
  src/step/step.controller.ts
  src/step/step.service.ts
Labels: feat

#13 feat: 임상 조회
  src/clinical/clinical.controller.ts
  src/clinical/clinical.service.ts
Labels: feat

#12 fix: 필드명 변경
  src/core/entities/core.entity.ts
Labels: feat

#18 fix:packge.json xml2json -> xml2json-light로 변경
  package-lock.json
  package.json
  src/clinical/clinical.service.ts
Labels: bug

#20 fix: xml2json
  src/clinical/clinical.service.ts
Labels: bug

#15 feat: 임상 리스트 / 검색
  package-lock.json
  package.json
  src/clinical/clinical.controller.ts
  src/clinical/clinical.repository.ts
  src/clinical/clinical.service.ts
  src/clinical/dto/Query.dto.ts
Labels: feat

#22 feat: 임상 리스트 / 검색
  package-lock.json
  src/clinical/clinical.repository.ts
  src/clinical/dto/Query.dto.ts
  src/clinical/entities/clinical.entity.ts
  src/step/entities/step.entity.ts
Labels: feat

#28 chore: 헤로쿠 설정 추가
  Procfile
Labels: feat

#35 test: clinical service 유닛 테스트
  src/clinical/clinical.service.spec.ts
  src/clinical/clinical.service.ts
Labels: test

#38 hot-fix: clinical 초기 데이터 입력
  .gitignore
  src/clinical/clinical.service.ts
Labels: bug, fix
